config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'questions#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_like
      patch :vote_dislike
      delete :revote
    end
  end

  concern :commentable do
      resources :comments
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :subscriptions, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, only: [:create, :update, :destroy], concerns: [:votable, :commentable] do
      patch :mark_as_best, on: :member
    end
  end
  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  resources :badges, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :index, on: :collection
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  get '/search', to: 'search#search'
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many_attached :files
  has_one :badge, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true
  validates :title, length: { maximum: 255 }

  after_create :subscribe_user!

  private

  def subscribe_user!
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [:show, :update, :destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    @question = Question.find(params[:id])
    render json: @question
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_resource_owner

    if @question.save
      render json: @question, status: :created
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :ok
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      head :ok
    else
      head :forbidden
    end
  end

  private

  def question_params
    params.require(:question).permit(:body, :title)
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  authorize_resource

  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  after_action :publish_question, only: [:create]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
    @answer.comments.new
    @question.comments.new
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @badge = @question.build_badge
  end

  def edit; end

  def create
    @question = current_user.questions.new(questions_params)

    if @question.save
      redirect_to @question, notice: 'You question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(questions_params) if current_user.author_of?(@question)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy if current_user.author_of?(@question)
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def questions_params
    params.require(:question).permit(:title, :body,
                                     files: [],
                                     links_attributes: [:name, :url],
                                     badge_attributes: [:name, :image])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast 'questions',
                                 ApplicationController.render( partial: 'questions/questions_links',
                                 locals: { question: @question })

  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_form.html.slim
= form_with model: [@question, @answer], class: 'new-answer' do |f|
  p= f.label :body
  = f.text_area :body
  p= f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  p= f.fields_for :links do |l|
    = render 'shared/link_template', f: l
  .links
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_template'

  p= f.submit 'Create answer'

app/views/questions/_question.html.slim
div class="question-#{question.id}"
  - cache question do
    h1= question.title
    p= question.body

  - if user_signed_in?
    = render partial: 'votes/vote', locals: { resource: question }

  - if can?(:create, Subscription)
    .subscribe-option id="#{question.id}"
      = render 'subscriptions/subscription', resource: question

  = render partial: 'show_question_files', locals: { question: question }

.question id=question.id
  - if can?(:update, question)

    = link_to 'Edit question', '#', class: 'edit-question-link'

    = form_with model: question, class: 'hidden', html: { id: "edit-question" } do |f|
      p= f.label :title
      = f.text_area :title
      p= f.label :body
      = f.text_area :body
      p= f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      p= f.fields_for :links do |l|
      .links
        = link_to_add_association 'add link', f, :links, partial: 'shared/link_template'
      p= f.submit 'Save'

    p= link_to 'Delete question',
            question_path(question),
            method: :delete

.question-comments class="comments-#{question.id}"
  - if user_signed_in?
    = render partial: 'comments/comment_form', locals: { resource: question }
    = render question.comments

app/views/questions/_questions_links.html.slim
div class="question-#{question.id}"
  h1= question.title
  p= question.body

  = link_to question.title, question_path(question)

app/views/questions/_show_question_files.html.slim
- if question.files.attached?
  - question.files.each do |file|
    div id=file.id class='file'
      p
        = link_to file.filename.to_s, url_for(file)
        - if can?(:destroy, question)
          p= link_to 'Delete file', file_path(file), method: :delete, remote: true

app/views/questions/_show_question_links.html.slim
p Links:
ul
  - @question.links.each do |link|
    div class="link-#{link.id}"
      - if link.url_gist_link?
        p
          b= link.gist_title
          br= link.gist_body
      li= link_to link.name, link.url
      - if can?(:destroy, link.linkable)
        = link_to 'Delete link', link_path(link), method: :delete, remote: true

app/views/questions/index.html.slim
- @questions.each do |q|
  p= link_to q.title, q

p= link_to 'Ask question', new_question_path

.questions
  = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title

  p
    = f.label :body
    = f.text_area :body

  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  p
    = f.fields_for :links do |l|
      = render 'shared/link_template', f: l
    .links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_template'

  p Badge:
  p
    = f.fields_for :badge do |b|
      p
        = b.label :name
        = b.text_field :name
      p
        = b.label :image
        = b.file_field :image
  p
    = f.submit 'Ask'

app/views/questions/show.html.slim
.question-show
  = render partial: 'questions/question', locals: { question: @question }

.question-links
  = render 'show_question_links'

.question-errors
  = render 'shared/errors', resource: @question

.answer-errors
  = render 'shared/errors', resource: @answer

.answers
  = render @question.answers

= render 'answer_form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question-show').html("<%= j render @question %>");
  $('.question-links').html("<%= j render partial: 'show_question_links' %>");
  $('#edit-question').addClass('hidden');
  $('.edit-question-link').show();
<% end %>