config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'questions#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  concern :votable do
    member do
      patch :vote_like
      patch :vote_dislike
      delete :revote
    end
  end

  concern :commentable do
      resources :comments
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :subscriptions, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, only: [:create, :update, :destroy], concerns: [:votable, :commentable] do
      patch :mark_as_best, on: :member
    end
  end
  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  resources :badges, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :index, on: :collection
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  get '/search', to: 'search#search'
  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  default_scope { order(best: :desc) }

  belongs_to :question, touch: true
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :send_mail_to_author, :subscription_notification_to_user

  def mark_as_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
      question.badge&.update!(user: user)
    end
  end

  private

  def send_mail_to_author
    NewAnswerMailer.new_answer(self).deliver_later
  end

  def subscription_notification_to_user
    NewAnswerNotifierJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  authorize_resource

  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:update, :destroy, :mark_as_best]
  after_action :publish_answer, only: [:create]

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    @question = @answer.question
  end

  def destroy
    @question = @answer.question
    @answer.destroy if current_user.author_of?(@answer)
  end

  def mark_as_best
    @answer.mark_as_best if current_user.author_of?(@answer.question)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("question_#{@answer.question_id}", { answer: @answer, links: @answer.links, files: files })
  end

  def files
    @answer.files.each_with_object([]) do |file, files|
      files.push({ url: url_for(file), name: file.filename.to_s })
    end
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: [:index, :create]
  before_action :load_answer, only: [:show, :update, :destroy]

  authorize_resource

  def index
    @answers = @question.answers
    render json: @answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, status: :ok
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      head :ok
    else
      head :forbidden
    end
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id = "answer-#{answer.id}" class=('best' if answer.best)
  - cache answer do
    p= answer.body

  div class="answer-#{answer.id}"
    - if user_signed_in?
      = render partial: 'votes/vote', locals: { resource: answer }

  .links
    p Links:
    ul
      - answer.links.each do |link|
        div class="link-#{link.id}"
          - if link.url_gist_link?
            p
              b= link.gist_title
              br= link.gist_body
          li= link_to link.name, link.url
          - if current_user&.author_of?(link.linkable)
            = link_to 'Delete link', link_path(link), method: :delete, remote: true

  .answer-comments class="comments-#{answer.id}"
    - if user_signed_in?
      = render partial: 'comments/comment_form', locals: { resource: answer }
      = render answer.comments

  = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |f|
    p= f.label :body, 'You answer'
    = f.text_area :body
    p= f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
    p= f.fields_for :links do |l|
    .links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_template'
    p= f.submit 'Save'

  - if can?(:update, answer)

    p= link_to 'Edit', '#', class: 'edit-answer-link', data: {answer_id: answer.id}
    p= link_to 'Delete answer', answer, method: :delete, remote: true

  - if can?(:update, answer.question)
    p= link_to 'Best answer', mark_as_best_answer_path(answer), class: 'mark-as-best', data: { answer_id: answer.id }, method: :patch, remote: true

  - if answer.files.attached?
    - answer.files.each do |file|
      div id=file.id class='file'
        p= link_to file.filename.to_s, url_for(file)
        - if current_user&.author_of?(answer)
          = link_to 'Delete file', file_path(file), method: :delete, remote: true

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('#answer-' + <%= @answer.id %>).remove();
<% end %>

app/views/answers/mark_as_best.js.erb
<% if @answer.best? %>
  $('<%="#answer-#{ @answer.id }" %>').addClass('best');
  $('.mark-as-best').removeClass('hidden');
  $(".mark-as-best[data-answer-id='<%= @answer.id %>']").addClass('hidden');
  $('#answer-<%= @answer.id %>').remove();
  $('.answers').prepend('<%= j render @answer %>');
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if !@answer.errors.present? %>
  $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>